sudo: required

services:
    - docker

language: go

go:
  - 1.5.3
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master

install:
  - make bootstrap

script:
  - make test
