sudo: required
dist: trusty

services:
    - docker

language: go

go:
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master

install:
  - make travis
  - make bootstrap

script:
  - travis_wait make test
