sudo: required
dist: trusty

services:
    - docker

language: go

go:
  -  1.9.x

git:
  depth: 300

branches:
  only:
    - master

matrix:
  include:
    - env:
    - env: RUN_UI_TESTS=1 SKIP_NOMAD_TESTS=1

cache:
  directories:
    - ui/node_modules

before_install:
    - sudo apt-get update
    - sudo apt-get install -y liblxc1 lxc-dev lxc shellcheck
    - sudo apt-get install -y qemu
    - sudo bash ./scripts/travis-rkt.sh
    - sudo bash ./scripts/travis-consul.sh
    - sudo bash ./scripts/travis-vault.sh

install:
  - make bootstrap

script:
  - sudo -E "PATH=$PATH" make travis
