sudo: required
dist: trusty

services:
    - docker

language: go

go:
  - 1.5.3
  - tip

env:
  - DOCKER_VERSION=1.9.1

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master

install:
  - make prepare_docker
  - make bootstrap

script:
  - make test
