steps:
  - run:
      name: Running Nomad Tests
      command: |
        if [ -z $GOTEST_PKGS_EXCLUDE ];
        then
          unset GOTEST_PKGS_EXCLUDE
        else
          unset GOTEST_PKGS
        fi

        if [ ! -z $GOTESTARCH ]; then
          export GOARCH="$GOTESTARCH";
        fi

        mkdir -p /tmp/test-reports
        sudo -E PATH="$GOPATH/bin:/usr/local/go/bin:$PATH" make generate-structs
        sudo -E PATH="$GOPATH/bin:/usr/local/go/bin:$PATH" make test-nomad
